# Generated by Django 4.2.2 on 2023-06-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.DecimalField('Цена', max_digits=10, decimal_places=2)),
                ('size', models.CharField(max_length=10)),
                ('full_text', models.TextField(verbose_name='Характеристика')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Мужские товары',
            },
        ),
    ]
