# Generated by Django 4.2.2 on 2023-06-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KUDINOV', '0002_acses_customer_order_review_women_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('payment_status', models.CharField(max_length=50, verbose_name='Статус оплаты')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.DeleteModel(
            name='Acses',
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'М-товар', 'verbose_name_plural': 'Мужсукие товары'},
        ),
        migrations.AlterModelOptions(
            name='women',
            options={'verbose_name': 'Ж-товар', 'verbose_name_plural': 'Женские товары'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='anons',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='full_text',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='anons',
        ),
        migrations.RemoveField(
            model_name='women',
            name='anons',
        ),
        migrations.AddField(
            model_name='articles',
            name='photo',
            field=models.ImageField(default='', upload_to='products/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другой')], default='M', max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='women',
            name='photo',
            field=models.ImageField(default='', upload_to='products/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='women',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='women',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='women',
            name='size',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_text',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='women',
            name='full_text',
            field=models.TextField(verbose_name='Характеристика'),
        ),
    ]
