# Generated by Django 4.2.2 on 2023-06-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KUDINOV', '0003_zakaz_delete_acses_alter_articles_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другой')], default='', max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(to='KUDINOV.product'),
        ),
    ]
