# Generated by Django 4.2.6 on 2023-11-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KUDINOV', '0004_product_alter_customer_gender_customer_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(to='KUDINOV.order'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Статья'),
        ),
    ]
