# Generated by Django 4.2.7 on 2023-11-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KUDINOV', '0006_historicalreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='products',
        ),
    ]
